### PR TITLE
Add ExtendedProviders to the double hashed client

### PR DESCRIPTION
**Pull request by ischasny**
* Add extended providers to double hashed client;
* Maintain `ProviderInfo`s cache at the client level instead of per-request. This is done to save up some time on roundtrips as well as to index `ContextualExtendedProviders` by `ContextID` for faster lookup times.

### CODE REVIEW

**Review by willscott — COMMENTED** [review]
is it worth adding prometheus metrics to the providercache so we have a sense of how big it is in memory and how much of a hit rate it's giving us?

**Comment by ischasny** [comment]
> is it worth adding prometheus metrics to the providercache so we have a sense of how big it is in memory and how much of a hit rate it's giving us?

Bear in mind - the library is going to sit on the client side (i.e. it's not a server side cache). Do we report into prometheus from the client libraries anywhere already?

**Review by willscott — APPROVED** [review]
don't need to report always, but worth having the metrics, and maybe a way to configure max cache sizing?

**Comment by ischasny** [comment]
> don't need to report always, but worth having the metrics, and maybe a way to configure max cache sizing?

Makes sense - will add GH issues for both.

**Pull request merged**
