### PR TITLE
Add script to generate random peer identity

### PR DESCRIPTION
**Pull request by masih**
## Context
Deployment of indexer nodes works with explicitly generated peer identity that is then encrypted and checked into code. Add a script that makes the generation of random identity easier. 

## Proposed Changes
Add a script to generate a random peer identity, used to instantiate
new indexer nodes. The script also prints out the peer ID from the
generated private key.

## Tests
Used to generate identities locally.

## Revert Strategy
`git revert`

### CODE REVIEW

**Review by MarcoPolo — CHANGES_REQUESTED** [review]
Should this hook into SOPS to encrypt the contents? I feel like writing the file out unencrypted (especially in `0666`) is a foot gun.

**Comment by masih** [comment]
> Should this hook into SOPS to encrypt the contents? I feel like writing the file out unencrypted (especially in `0666`) is a foot gun.

Are you suggesting calling SOPS directly from go? Sure we can do that. 
My thinking was to do the glueing in bash as a `make` target once manifests are merged to master.

**Comment by MarcoPolo** [comment]
> Are you suggesting calling SOPS directly from go? Sure we can do that.
yep that's what I was suggesting.

We can use make instead, but I'd like to avoid the footgun if someone ran this manually.

What if the secret was output to stdout and the file was used to write the public peer id? That way you have to handle the secret material within the process and you can't accidentally commit a file with secrets. In the make script it can use a temp file for the peer id and delete it once it finishes.

**Comment by masih** [comment]
Yup thank you for pointing this out; I'll have another go to see how I can make this safe. 

Side note: Re Peer ID printing, that's just so we know what the peer ID of the node would be. I made changes to the config [a while back](https://github.com/filecoin-project/storetheindex/pull/296) which makes peer ID optional if private key is specified, since it can be generated from private key, and assert that if it is specified it's consistent with private key.

**Pull request closed without merging**
