### PR TITLE
Connect dhstores to indexstar in dev

### PR DESCRIPTION
**Pull request by ischasny**

### CODE REVIEW

**Comment by masih** [comment]
what is the rationale for this? Does this not already happen via dhfind backends corresponding to those dhstores?

**Comment by ischasny** [comment]
> what is the rationale for this? Does this not already happen via dhfind backends corresponding to those dhstores?

DHstores used to be connected to indexstar but got removed probably by mistake in one of the latest PRs. DHFinds don't serve EncryptedValueKeys.

**Comment by masih** [comment]
I see thanks

**Review by masih — APPROVED** [review]
looking forward to combining dhstore and dhfind

**Pull request merged**
